site_name: Mecons
site_url: https://www.brecons.net
site_description: Project documentation with Markdown.
site_author: MkDocs Team
nav:
    - Overview: 'index.md'
    - User Guide:
        - 'Requirements': 'requirements.md'
        - 'Create new Project': 'create-new-project.md'
    - Localization: 'localization.md'
theme: readthedocs