site_name: Mecons
site_url: https://www.brecons.net
site_description: Project documentation with Markdown.
site_author: MkDocs Team
nav:
    - Home: index.md
    - About: GettingStarted.md
theme: readthedocs