site_name: Mecons Tag Helper
site_url: https://www.brecons.net
site_description: An enterprise Tag Helper Library for Metronic - the most complete and trusted admin theme.
site_author: Bremus Solutions
repo_name: https://github.com/brecons/metronic-tag-helper.git

theme: readthedocs
extra_css:
  - css/mkdocs.css
markdown_extensions:
  - admonition

nav:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Localization: 'localization.md'
    - Change Log: 'change-log.md'
    - Layout:
        - 'Grid System': 'layout/grid-system.md'
        - 'Stack': 'layout/stack.md'
    - Components:
        - 'Alert': 'components/alert.md'
        - 'Datatable': 'components/datatable.md'
        - 'Modal': 'components/modal.md'
        - 'Popover': 'components/popover.md'
        - 'Progress': 'components/progress.md'
        - 'Tooltip': 'components/tooltip.md'
    - Content:
        - 'Anchor': 'content/anchor.md'
        - 'Badge': 'content/badge.md'
        - 'Icon': 'content/icon.md'
        - 'Portlet': 'content/portlet.md'
        - 'Progress Widget': 'content/progress-widget.md'
        - 'Stats Widget': 'content/stats-widget.md'
        - 'Table': 'content/table.md'
        - 'Tabs': 'content/tabs.md'
        - 'Timeline': 'content/timeline.md'
    - Forms:
        - 'Form Layout': 'forms/form-layout.md'
        - 'Form Controls': 'forms/form-controls.md'
        - 'Label and Help': 'forms/label-and-help.md'
        - 'Input': 'forms/input.md'
        - 'Textarea': 'forms/textarea.md'
        - 'Select': 'forms/select.md'
        - 'Static': 'forms/static.md'
        - 'Checkbox List': 'forms/checkbox-list.md'
        - 'Radio List': 'forms/radio-list.md'
        - 'Switch': 'forms/switch.md'
        - 'Touchspin': 'forms/touchspin.md'
        - 'Data Annotation': 'forms/data-annotation.md'
        - 'Validation': 'forms/validation.md'
    - Buttons:
        - 'Button': 'forms/button.md'
        - 'Dropdown Button': 'forms/dropdown-button.md'
        - 'Button Group': 'forms/button-group.md'
    - Date and Time:
        - 'Datepicker': 'forms/datepicker.md'
        - 'Daterangepicker': 'forms/daterangepicker.md'
        - 'Timepicker': 'forms/timepicker.md'
    - Editors:
        - 'Markdown': 'forms/markdown.md'
        - 'Summernote': 'forms/summernote.md'
    - Miscellaneous:
        - 'Dropzone': 'forms/dropzone.md'
        - 'NoUiSlider': 'forms/nouislider.md'

copyright: Copyright &copy; 2017 - 2019 <a href="https://www.bremus-solutions.de">Bremus Solutions</a>. All Right Reserved.

plugins:
    - search